version: 2
project_name: terraform-provider-hri
before:
  hooks:
    - go mod tidy
builds:
  - id: provider
    binary: "{{ .ProjectName }}_v{{ .Version }}"
    env: [CGO_ENABLED=0]
    goos: [linux, darwin, windows, freebsd]
    goarch: [amd64, arm64]
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{ .Version }}
archives:
  - formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files: [README.md, LICENSE, docs/**]
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  extra_files:
    - glob: ./terraform-registry-manifest.json
      name_template: "{{ .ProjectName }}_{{ .Version }}_manifest.json"
signs:
  - cmd: gpg
    args: ["--batch", "--local-user", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]
    artifacts: checksum
release:
  github:
    owner: withlogicco
    name: terraform-provider-hri
  extra_files:
    - glob: ./terraform-registry-manifest.json
      name_template: "{{ .ProjectName }}_{{ .Version }}_manifest.json"
